<a href="https://colab.research.google.com/github/gmdeorozco/Scikit-Learn-Library/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
array = np.array([[3.0,3.0,3.0,91.5],[5.0,2.0,4.0,128],[8.0,3.0,5.0,198.5],[9.0,7.0,9.0,260.5],[5.0,8.0,8.0,184],[6.0,4.0,1.0,151.5],[2.0,6.0,3.0,92.5],[1.0,9.0,9.0,114.5],[3.0,5.0,0.0,95],[6.0,2.0,6.0,155],[9.0,1.0,4.0,201],[10.0,2.0,3.0,224.5],[11.0,6.0,2.0,269],[5.0,2.0,1.0,117.5],[3.0,1.0,5.0,84.5],[4.0,5.0,3.0,125.5],[5.0,7.0,5.0,166.5],[2.0,2.0,2.0,61],[6.0,1.0,6.0,148],[2.0,5.0,2.0,82],[1.0,3.0,1.0,44.5],[5.0,5.0,5.0,152.5],[7.0,2.0,7.0,178.5],[4.0,6.0,2.0,129],[4.0,2.0,1.0,97.5],[45.0,1.0,5.0,924.5],[9.0,5.0,3.0,225.5],[28.0,7.0,5.0,626.5],[32.0,4.0,2.0,675],[21.0,4.0,6.0,469],[2.0,7.0,2.0,96],[1.0,45.0,1.0,338.5],[2.0,23.0,5.0,218.5],[3.0,22.0,7.0,238.5],[4.0,11.0,4.0,171],[5.0,12.0,4.0,198],[4.0,1.0,1.0,90.5],[4.0,5.0,5.0,132.5],[7.0,3.0,3.0,171.5],[45.0,5.0,5.0,952.5],[23.0,2.0,2.0,481],[22.0,6.0,6.0,503],[11.0,2.0,2.0,241],[12.0,1.0,1.0,250.5],[4.0,5.0,5.0,132.5],[4.0,7.0,7.0,153.5],[7.0,1.0,1.0,150.5],[45.0,5.0,5.0,952.5],[23.0,3.0,3.0,491.5],[22.0,5.0,5.0,492.5],[11.0,2.0,2.0,241],[12.0,6.0,6.0,303],[4.0,2.0,2.0,101],[4.0,1.0,1.0,90.5],[7.0,5.0,5.0,192.5],[45.0,7.0,7.0,973.5],[23.0,1.0,1.0,470.5],[22.0,5.0,5.0,492.5],[11.0,3.0,3.0,251.5],[12.0,5.0,5.0,292.5],[4.0,2.0,2.0,101],[4.0,6.0,6.0,143],[7.0,2.0,2.0,161],[45.0,1.0,1.0,910.5],[23.0,5.0,5.0,512.5],[22.0,7.0,7.0,513.5],[11.0,1.0,1.0,230.5],[12.0,5.0,5.0,292.5],[4.0,3.0,3.0,111.5],[4.0,5.0,5.0,132.5],[7.0,2.0,2.0,161],[45.0,6.0,6.0,963],[23.0,2.0,2.0,481],[22.0,1.0,1.0,450.5],[11.0,5.0,5.0,272.5],[12.0,7.0,2.0,296],[4.0,1.0,1.0,90.5],[4.0,5.0,5.0,132.5],[7.0,3.0,3.0,171.5],[45.0,5.0,5.0,952.5],[23.0,2.0,2.0,481],[22.0,6.0,1.0,485.5],[11.0,2.0,5.0,251.5],[12.0,1.0,1.0,250.5],[4.0,5.0,5.0,132.5],[4.0,7.0,7.0,153.5],[7.0,1.0,3.0,157.5],[45.0,5.0,5.0,952.5],[23.0,3.0,2.0,488],[22.0,5.0,1.0,478.5],[11.0,2.0,5.0,251.5],[12.0,6.0,1.0,285.5],[4.0,2.0,5.0,111.5],[4.0,1.0,7.0,111.5],[7.0,5.0,3.0,185.5],[45.0,7.0,5.0,966.5],[23.0,1.0,2.0,474],[22.0,5.0,1.0,478.5],])

In [34]:
import pandas as pd
df = pd.DataFrame(array, columns = ['X', 'Y', 'Z', 'RESULT'])

In [35]:
df.head()

     X    Y    Z  RESULT
0  3.0  3.0  3.0    91.5
1  5.0  2.0  4.0   128.0
2  8.0  3.0  5.0   198.5
3  9.0  7.0  9.0   260.5
4  5.0  8.0  8.0   184.0

In [41]:
from sklearn.linear_model import LinearRegression
regression_model = LinearRegression()
train_x = df.sample(frac=0.8,random_state=0)
test_x = df.drop(train_x.index)

train_x

       X    Y    Z  RESULT
26   9.0  5.0  3.0   225.5
85   4.0  7.0  7.0   153.5
2    8.0  3.0  5.0   198.5
55  45.0  7.0  7.0   973.5
68   4.0  3.0  3.0   111.5
..   ...  ...  ...     ...
96  23.0  1.0  2.0   474.0
69   4.0  5.0  5.0   132.5
20   1.0  3.0  1.0    44.5
92   4.0  2.0  5.0   111.5
72  23.0  2.0  2.0   481.0

[78 rows x 4 columns]

In [42]:
test_x

       X    Y    Z  RESULT
9    6.0  2.0  6.0   155.0
12  11.0  6.0  2.0   269.0
21   5.0  5.0  5.0   152.5
25  45.0  1.0  5.0   924.5
36   4.0  1.0  1.0    90.5
37   4.0  5.0  5.0   132.5
39  45.0  5.0  5.0   952.5
44   4.0  5.0  5.0   132.5
46   7.0  1.0  1.0   150.5
47  45.0  5.0  5.0   952.5
58  11.0  3.0  3.0   251.5
64  23.0  5.0  5.0   512.5
65  22.0  7.0  7.0   513.5
67  12.0  5.0  5.0   292.5
70   7.0  2.0  2.0   161.0
77   4.0  5.0  5.0   132.5
81  22.0  6.0  1.0   485.5
83  12.0  1.0  1.0   250.5
87  45.0  5.0  5.0   952.5
94   7.0  5.0  3.0   185.5

In [43]:
train_y = train_x.pop('RESULT')
train_x

       X    Y    Z
26   9.0  5.0  3.0
85   4.0  7.0  7.0
2    8.0  3.0  5.0
55  45.0  7.0  7.0
68   4.0  3.0  3.0
..   ...  ...  ...
96  23.0  1.0  2.0
69   4.0  5.0  5.0
20   1.0  3.0  1.0
92   4.0  2.0  5.0
72  23.0  2.0  2.0

[78 rows x 3 columns]

In [44]:
train_y

26    225.5
85    153.5
2     198.5
55    973.5
68    111.5
      ...
96    474.0
69    132.5
20     44.5
92    111.5
72    481.0
Name: RESULT, Length: 78, dtype: float64

In [45]:
regression_model.fit(train_x,train_y)

LinearRegression()

In [48]:
regression_model.predict([[5,2,4]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([128.])